/*
** TailwindCSS Configuration File
**
** Docs: https://tailwindcss.com/docs/configuration
** Default: https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
*/

// load default theme settings
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors')

const additionalSpacing = {
    '14' : '3.5rem',
    '84' : '21rem',
    '160': '40rem',
};

module.exports = {
    purge: [
        './resources/**/*.blade.php',
        './resources/**/*.html',
        './resources/**/*.vue',
    ],
    theme: {
        fontFamily: {
            'sans': ['Poppins', ...defaultTheme.fontFamily.sans],
            'sans-landlord': ['Inter', ...defaultTheme.fontFamily.sans],
        },
        extend: {
            animation: {
                'spin-slow': 'spin 1.5s linear infinite',
            },
            boxShadow: {
                'subtle': '0px 0px 32px 0px rgba(136, 152, 170, 0.15)',
            },
            borderRadius: {
                'xl':  '1rem',
                '2xl':  '2rem',
            },
            colors: {
                cyan: colors.cyan,
                gray: {
                    ...colors.blueGray,
                    '150': '#F4F7FA',
                    '850': '#222938'
                },
                mono: colors.gray,
                navy: {
                    100: '#E6E7EA',
                    200: '#C2C4CC',
                    300: '#999CAA',
                    400: '#707487',
                    500: '#51576E',
                    600: '#323954',
                    700: '#2D334D',
                    800: '#262C43',
                    850: '#1F243A',
                    900: '#131729',
                },
                orange: colors.orange,
                theme: {
                    'base'                          : 'var(--color-base)',
                    'base-contrast'                 : 'var(--color-base-contrast)',
                    'base-subtle'                   : 'var(--color-base-subtle)',
                    'base-subtle-contrast'          : 'var(--color-base-subtle-contrast)',
                    'card'                          : 'var(--color-card)',
                    'card-contrast'                 : 'var(--color-card-contrast)',
                    'danger'                        : 'var(--color-danger)',
                    'danger-contrast'               : 'var(--color-danger-contrast)',
                    'danger-hover'                  : 'var(--color-danger-hover)',
                    'danger-hover-contrast'         : 'var(--color-danger-hover-contrast)',
                    'info'                          : 'var(--color-info)',
                    'info-contrast'                 : 'var(--color-info-contrast)',
                    'info-hover'                    : 'var(--color-info-hover)',
                    'info-hover-contrast'           : 'var(--color-info-contrast-hover)',
                    'primary'                       : 'var(--color-primary)',
                    'primary-contrast'              : 'var(--color-primary-contrast)',
                    'primary-hover'                 : 'var(--color-primary-hover)',
                    'primary-hover-contrast'        : 'var(--color-primary-hover-contrast)',
                    'primary-subtle'                : 'var(--color-primary-subtle)',
                    'primary-subtle-contrast'       : 'var(--color-primary-subtle-contrast)',
                    'primary-subtle-hover'          : 'var(--color-primary-subtle-hover)',
                    'primary-subtle-hover-contrast' : 'var(--color-primary-subtle-hover-contrast)',
                    'success'                       : 'var(--color-success)',
                    'success-contrast'              : 'var(--color-success-contrast)',
                    'success-hover'                 : 'var(--color-success-hover)',
                    'success-hover-contrast'        : 'var(--color-success-hover-contrast)',
                    'warning'                       : 'var(--color-warning)',
                    'warning-contrast'              : 'var(--color-warning-contrast)',
                    'warning-hover'                 : 'var(--color-warning-hover)',
                    'warning-hover-contrast'        : 'var(--color-warning-hover-contrast)',
                },
            },
            margin: {
                'px': '1px'
            },
            minWidth: {
                ...defaultTheme.spacing,
                ...additionalSpacing
            },
            ringColor: {
                primary: 'var(--ring-color-primary)'
            },
            spacing: additionalSpacing,
            transitionProperty: {
                'height': 'height',
                'spacing': 'margin, padding',
            }
        },
    },
    variants: {
        accessibility: ['responsive', 'focus-within', 'focus'],
        alignContent: ['responsive'],
        alignItems: ['responsive'],
        alignSelf: ['responsive'],
        animation: ['responsive'],
        appearance: ['responsive'],
        backgroundAttachment: ['responsive'],
        backgroundClip: ['responsive'],
        backgroundColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        backgroundImage: ['responsive'],
        backgroundOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        backgroundPosition: ['responsive'],
        backgroundRepeat: ['responsive'],
        backgroundSize: ['responsive'],
        borderCollapse: ['responsive'],
        borderColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        borderOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        borderRadius: ['responsive', 'hover'],
        borderStyle: ['responsive'],
        borderWidth: ['responsive', 'hover'],
        boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        boxSizing: ['responsive'],
        clear: ['responsive'],
        container: ['responsive'],
        cursor: ['responsive'],
        display: ['responsive'],
        divideColor: ['responsive', 'dark'],
        divideOpacity: ['responsive'],
        divideStyle: ['responsive'],
        divideWidth: ['responsive'],
        fill: ['responsive'],
        flex: ['responsive'],
        flexDirection: ['responsive'],
        flexGrow: ['responsive'],
        flexShrink: ['responsive'],
        flexWrap: ['responsive'],
        float: ['responsive'],
        fontFamily: ['responsive'],
        fontSize: ['responsive'],
        fontSmoothing: ['responsive'],
        fontStyle: ['responsive'],
        fontVariantNumeric: ['responsive'],
        fontWeight: ['responsive', 'hover', 'focus'],
        gap: ['responsive'],
        gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
        gridAutoColumns: ['responsive'],
        gridAutoFlow: ['responsive'],
        gridAutoRows: ['responsive'],
        gridColumn: ['responsive'],
        gridColumnEnd: ['responsive'],
        gridColumnStart: ['responsive'],
        gridRow: ['responsive'],
        gridRowEnd: ['responsive'],
        gridRowStart: ['responsive'],
        gridTemplateColumns: ['responsive'],
        gridTemplateRows: ['responsive'],
        height: ['responsive'],
        inset: ['responsive'],
        justifyContent: ['responsive'],
        justifyItems: ['responsive'],
        justifySelf: ['responsive'],
        letterSpacing: ['responsive'],
        lineHeight: ['responsive'],
        listStylePosition: ['responsive'],
        listStyleType: ['responsive'],
        margin: ['responsive', 'hover'],
        maxHeight: ['responsive'],
        maxWidth: ['responsive'],
        minHeight: ['responsive'],
        minWidth: ['responsive'],
        objectFit: ['responsive'],
        objectPosition: ['responsive'],
        opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        order: ['responsive'],
        outline: ['responsive', 'focus-within', 'focus'],
        overflow: ['responsive'],
        overscrollBehavior: ['responsive'],
        padding: ['responsive', 'hover'],
        placeContent: ['responsive'],
        placeItems: ['responsive'],
        placeSelf: ['responsive'],
        placeholderColor: ['responsive', 'dark', 'focus'],
        placeholderOpacity: ['responsive', 'focus'],
        pointerEvents: ['responsive'],
        position: ['responsive'],
        resize: ['responsive'],
        ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
        ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus'],
        ringOffsetWidth: ['responsive', 'focus-within', 'focus'],
        ringOpacity: ['responsive', 'focus-within', 'focus'],
        ringWidth: ['responsive', 'focus-within', 'focus'],
        rotate: ['responsive', 'hover', 'focus'],
        scale: ['responsive', 'hover', 'focus'],
        skew: ['responsive', 'hover', 'focus'],
        space: ['responsive'],
        stroke: ['responsive'],
        strokeWidth: ['responsive'],
        tableLayout: ['responsive'],
        textAlign: ['responsive'],
        textColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
        textDecoration: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        textOpacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
        textOverflow: ['responsive'],
        textTransform: ['responsive'],
        transform: ['responsive'],
        transformOrigin: ['responsive'],
        transitionDelay: ['responsive'],
        transitionDuration: ['responsive'],
        transitionProperty: ['responsive'],
        transitionTimingFunction: ['responsive'],
        translate: ['responsive', 'hover', 'focus'],
        userSelect: ['responsive'],
        verticalAlign: ['responsive'],
        visibility: ['responsive'],
        whitespace: ['responsive'],
        width: ['responsive'],
        wordBreak: ['responsive'],
        zIndex: ['responsive', 'focus-within', 'focus'],
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('@tailwindcss/forms')
    ]
};
